services:
  marzban:
    build:
      context: .
      args:
        XRAY_VERSION: v26.1.23
    image: shaykhraziev2b/marzban:unstable-dev
    restart: unless-stopped
    env_file: .env
    environment:
      XRAY_EXECUTABLE_PATH: /usr/local/bin/xray
    ports:
      - "8000:8000"
      - "443:443"
    volumes:
      - ./marzban:/var/lib/marzban
