services:
  marzban:
    image: shaykhraziev2b/marzban:unstable-dev
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
      - "443:443"
    volumes:
      - ./marzban:/var/lib/marzban
